-- Phase 1 seed: Ben's profile values.
-- Constraints from CLAUDE.md / PROJECT-BRIEF §1 are encoded here, not in prompt:
--   firstName = Benjamin; address = Apollo Beach (NOT Riverview); $60K salary floor;
--   veteran YES; disability YES; race/ethnicity intentionally UNSET (never auto-answered);
--   approved skills only (no AI, no Lofty/SkySlope/CRM/Google Ads); $36M annual SST volume;
--   Closing Day = sales pipeline analytics platform.
-- updated_at uses a fixed seed timestamp; the API overwrites it on every edit.

INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('firstName', '"Benjamin"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('lastName', '"Whetstone"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('email', '"brwhetstone@gmail.com"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('phone', '"813-468-9832"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('address', '"6514 Maiden Sea Dr"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('city', '"Apollo Beach"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('state', '"FL"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('zip', '"33572"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('country', '"USA"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('citizenship', '"US Citizen"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('driverLicense', 'true', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('minimumAgeRequirement', 'true', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('linkedinProfile', '"linkedin.com/in/benwhetstone"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('portfolioLink', '"data.benwhetstone.info"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('veteranStatus', '"PROTECTED_VETERAN"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('disabilityStatus', '"YES"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('gender', '"PREFER_NOT_TO_SAY"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('lgbtqCommunity', '"PREFER_NOT_TO_SAY"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('legalSetup', '["US_FULL_TIME_EMPLOYEE_W2"]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('residenceCountry', '"USA"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('workAuthorization', '["US_CITIZEN"]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('visaSponsorship', '"NO"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('workingOutside', '["US"]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('baseSalary', '60000', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('baseSalaryPeriod', '"YEARLY"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('employmentType', '["FULL_TIME"]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('workFormat', '["REMOTE", "HYBRID", "ON_SITE"]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('relocationReadiness', '"DEPENDS_ON_LOCATION"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('relocationArea', '["US_OPEN_WITHIN_STATE"]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('noticePeriod', '"TWO_WEEKS"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('schedule', '"FLEXIBLE"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('benefits', '["HEALTH_INSURANCE", "RETIREMENT_PLAN", "PAID_TIME_OFF", "LEARNING_BUDGET"]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('academicLevel', '"MASTER"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('fieldOfStudy', '["Public Administration", "Business Administration"]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('institutionName', '"Troy University"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('seniorityLevel', '"ENTRY_WITH_DEGREE"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('leadershipExperience', 'true', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('processesAndMethodologies', '["TARGET_DRIVEN_KPI_OKR", "AGILE_SCRUM_KANBAN"]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('technicalToolbox', '["SQL", "T-SQL", "Power BI", "Microsoft Excel", "Google Sheets", "Data Analysis", "Data Visualization"]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('portfolioWebsites', '["data.benwhetstone.info"]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('st_hardSkills', '[{"name": "SQL", "level": "ADVANCED"}, {"name": "T-SQL", "level": "ADVANCED"}, {"name": "Power BI", "level": "INTERMEDIATE"}, {"name": "Microsoft Excel", "level": "ADVANCED"}, {"name": "Google Sheets", "level": "ADVANCED"}, {"name": "Data Analysis", "level": "ADVANCED"}, {"name": "Data Visualization", "level": "INTERMEDIATE"}, {"name": "Relational Data Modeling", "level": "INTERMEDIATE"}]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('st_softSkills', '[{"name": "Stakeholder Communication"}, {"name": "Requirements Gathering"}, {"name": "Attention to Detail"}, {"name": "Problem Solving"}]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('st_jobTitles', '[{"name": "Data Analyst"}, {"name": "Operations & Data Analyst"}, {"name": "Business Analyst"}]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('st_industryDomainKnowledge', '[{"name": "Real Estate"}, {"name": "SaaS"}, {"name": "Operations"}]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('st_workExperiences', '[{"title": "Operations & Data Analyst", "employer": "Closing Day", "startDate": "2026-01", "endDate": null, "city": "Apollo Beach, FL", "description": "Sales pipeline analytics platform. Designed the relational data model and the scoring logic that ranks client records on past performance."}, {"title": "Operations & Data Analyst", "employer": "The South Shore Team", "startDate": "2016-01", "endDate": null, "city": "Apollo Beach, FL", "description": "Residential real estate sales team, $36 million in annual transaction volume. Reconcile CRM, MLS, transaction management, and bookkeeping into one set of numbers."}]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('st_professionalCredential', '[{"name": "Microsoft Certified: Azure Data Fundamentals (DP-900)"}, {"name": "Google Data Analytics Foundations"}, {"name": "Introduction to SQL and Intermediate SQL, DataCamp"}]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('workLanguage', '[{"name": "English", "level": "NATIVE"}]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('companyMaturityFit', '"SOME_DEFINED_SOME_BUILDING"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('teamSetup', '"LEAN_TO_SPECIALISTS"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('teamSize', '"SMALL_TEAMS"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('culturalDiversityExperience', '"EXTENDED_PERIOD"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('areaOfInterest', '["Real Estate", "SaaS", "Analytics", "Operations"]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('workStatus', '"SELF_EMPLOYED"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('jobSearchIntensity', '"ACTIVELY_APPLYING"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('jobSearchDuration', '"ONE_TO_THREE_MONTHS"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('personalDeadline', '"WITHIN_2_3_MONTHS"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('searchTrigger', '"CAREER_CHANGE"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('searchMotivation', '["HIGHER_PAY", "MORE_LEARNING_GROWTH", "MORE_STABILITY"]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('motivationFit', '["FINANCIAL_STABILITY", "LEARNING_DEVELOPMENT", "NEW_DIRECTION"]', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('developmentFocus', '"GO_DEEPER"', '2026-07-28T00:00:00Z');
INSERT OR REPLACE INTO profile_values (field_key, value_json, updated_at) VALUES ('careerAspiration', '"Become a strong, well-rounded data analyst on a team where I can go deep on SQL, BI, and analytics engineering."', '2026-07-28T00:00:00Z');
